modLoader="javafml"
loaderVersion="[39,)"
license="MIT"

[[mods]]
modId="stacker"
version="${version}"
displayName="Stacker-Forge"
logoFile="icon.png"
description='''
Change the stack size of all items!
'''
credits="Andrew6rant (Andrew Grant),TexTrue"
authors="TexTrueStudio"